#!/usr/bin/env bash

SOURCES=${SOURCES-/sources}
OUTPUT=${OUTPUT-${SOURCES}}
WORKSPACE=${WORKSPACE-/workspace}

[[ -z ${SRPM_ONLY} ]] \
    && RPMBUILD_MODE="-ba" \
    || RPMBUILD_MODE="-bs"

RPM_BUILD_SOURCES=$(rpmbuild --eval '%{_sourcedir}')
RPM_BUILD_RPMS=$(rpmbuild --eval '%{_rpmdir}')
RPM_BUILD_SRPMS=$(rpmbuild --eval '%{_srcrpmdir}')

# make a copy
cp -R ${SOURCES}/* ${WORKSPACE}/.

# fix permissions on working copy
chown root:root ${WORKSPACE}/*

# copy any non-spec files/dirs to source directory
find ${WORKSPACE} -mindepth 1 -maxdepth 1 ! -name "*.spec" \
    -exec cp -R {} ${RPM_BUILD_SOURCES}/. \;

BUILDDEP_CMD=yum-builddep
command -v dnf > /dev/null 2>&1 && BUILDDEP_CMD="dnf builddep"

# install deps and fetch any external sources
# then do an RPM BUILD
find ${WORKSPACE} -maxdepth 1 -type f -name "*.spec" \
    -exec ${BUILDDEP_CMD} -y {} \; \
    -exec spectool --sourcedir --get-files {} \; \
    -exec rpmbuild ${RPMBUILD_OPTS} ${RPMBUILD_MODE} --clean {} \;

# extract RPMs
find ${RPM_BUILD_RPMS} -name "${COMPONENT}*.rpm" \
    -exec mv {} ${OUTPUT} \;

# extract SRPMs
find ${RPM_BUILD_SRPMS} -name "${COMPONENT}*.rpm" \
    -exec mv {} ${OUTPUT} \;

# fix uids
if [ -v OUTPUT_UID ]; then
   chown -R ${OUTPUT_UID}:${OUTPUT_UID} ${OUTPUT}/*
fi
